name: overlay_search
description: You can show overlay search widget with this package.
version: 0.0.3
homepage: https://furkanacar.dev
repository: https://github.com/AcarFurkan/overlay_search

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
